name: "Ricardo Lopes"
author: "Ricardo Lopes"
description: "Hacker, tech enthusiast, learner, judo black belt and occasional blogger"

url: "http://ricardolopes.net"
blog: "http://ricardolopes.net/blog/"
feed: "http://feeds.feedburner.com/ricardolopes/blog"
code_repo: "https://github.com/rplopes/ricardolopes.net"

email: "mail@ricardolopes.net"
twitter: ricardoplopes
github: rplopes
linkedin: ricardopintolopes

paginate: 10
paginate_path: "/blog/:num/"

permalink: "/blog/:title"

highlighter: pygments
markdown: kramdown
